-- 코드를 작성해주세요
SELECT COUNT(ID) AS 'FISH_COUNT'
FROM FISH_INFO
WHERE FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS') or FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'SNAPPER')